

# -- base activation source script from install/base.sh --
# -- [https://github.com/vivaxgen/install] --

# required environment variables
#   VVG_BASEDIR
#   uMAMBA_ENVNAME

# optional environment variables
#   VVG_PROMPT

PATH=${VVG_BASEDIR}/bin:${PATH}
export APPTAINER_DIR=${VVG_BASEDIR}/opt/apptainer

if [[ -z ${__IN_VVG_INSTALLATION__:-} ]]; then
  if [[ -z ${MAMBA_ROOT_PREFIX:-} ]]; then
    export MAMBA_ROOT_PREFIX=${VVG_BASEDIR}/opt/umamba
  fi
  eval "$(micromamba shell hook -s posix)"
  micromamba activate ${uMAMBA_ENVNAME}
fi

# from this point, readlink and dirname are already available

_script="$(readlink -f ${BASH_SOURCE[0]})"

# Delete last component from $_script
_mydir="$(dirname $_script)"

# add VVGBIN rather than adding to path, to minimize name collision
export VVGBIN="$(dirname $_mydir)/bin"

function reload_vvg_profiles {
  for rc in ${VVG_BASEDIR}/etc/bashrc.d/*; do
    if [ -f "$rc" ]; then
        # source file but prevent from exiting if errors occur
        . "$rc" || true
    fi
  done
  unset rc
  return 0
}

reload_vvg_profiles


# EOF
