

# -- base activation source script from install/base.sh --
# -- [https://github.com/vivaxgen/install] --

# required environment variables
#   VVG_BASEDIR
#   PIXI_ENVNAME

# optional environment variables
#   VVG_PROMPT

PATH=${VVG_BASEDIR}/bin:${PATH}
export PIXI_HOME=${VVG_BASEDIR}/opt/pixi/global
export PIXI_CACHE_DIR=${PIXI_HOME}/.cache
export PIP_CACHE_DIR=${PIXI_HOME}/.cache-pip
export RATTLER_AUTH_FILE=${PIXI_HOME}/.rattler-credentials.json
export APPTAINER_DIR=${VVG_BASEDIR}/opt/apptainer

if [[ -z ${__IN_VVG_INSTALLATION__:-} ]]; then
  eval "$(pixi shell-hook --manifest-path "${VVG_BASEDIR}/opt/pixi/${PIXI_ENVNAME}/pixi.toml")"
fi

# from this point, readlink and dirname are already available

_script="$(readlink -f ${BASH_SOURCE[0]})"

# Delete last component from $_script
_mydir="$(dirname $_script)"

# add VVG_REPODIR for the vvg-base repository
export VVG_REPODIR="$(dirname $_mydir)"

# add VVGBIN rather than adding to path, to minimize name collision
export VVGBIN="${VVG_REPODIR}/bin"

function reload_vvg_profiles {
  for rc in ${VVG_BASEDIR}/etc/bashrc.d/[0-9][0-9]-*; do
    if [ -f "$rc" ]; then
        # source file but prevent from exiting if errors occur
        . "$rc" || true
    fi
  done
  unset rc
  return 0
}

reload_vvg_profiles


# EOF
